version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=ndnn
      - POSTGRES_DB=roommate_DB
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

        